POST http://localhost:8080/api/groups/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExNywiZW1haWwiOiJyb2RyaWdvYWxhbmlzZnN3ZEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJtYWlsX2NvbmZpcm1lZCI6dHJ1ZSwiaWF0IjoxNjYyMzEwNTM0LCJleHAiOjE2NjIzMTE0MzR9.8ZtJag0vGhWWKywA5Iy9Jq8cDcca71rnAxkoNzx7IJc

{
    "name": "Colors"
}

### 

GET http://localhost:8080/api/groups/

### 

GET http://localhost:8080/api/groups/3

### 

PUT http://localhost:8080/api/groups/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExNywiZW1haWwiOiJyb2RyaWdvYWxhbmlzZnN3ZEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJtYWlsX2NvbmZpcm1lZCI6dHJ1ZSwiaWF0IjoxNjYyMzA5NTY2LCJleHAiOjE2NjIzMTA0NjZ9.yHDxFOcSMRsRoFqtpWPY-6cxyNpmkWFAQiLhJsdzx_w

{
    "id": 2,
    "name": "Animals Updated"
}

### 

DELETE http://localhost:8080/api/groups/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExNywiZW1haWwiOiJyb2RyaWdvYWxhbmlzZnN3ZEBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJtYWlsX2NvbmZpcm1lZCI6dHJ1ZSwiaWF0IjoxNjYyMzA5NTY2LCJleHAiOjE2NjIzMTA0NjZ9.yHDxFOcSMRsRoFqtpWPY-6cxyNpmkWFAQiLhJsdzx_w