POST http://localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoicm9kcmlnb2FsYW5pc2Zzd2RAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwibWFpbF9jb25maXJtZWQiOnRydWUsImlhdCI6MTY2ODk3NzQ5NywiZXhwIjoxNjY4OTc4Mzk3fQ.V1vWwN3ZBDWAv5rGxi21k6slUGHjom0XXElX5CIcnUM

{
    "id": 2
}