POST http://localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoicm9kcmlnb2FsYW5pc2Zzd2RAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwibWFpbF9jb25maXJtZWQiOnRydWUsImlhdCI6MTY3MDE5MzAwOSwiZXhwIjoxNjcwMTkzOTA5fQ.6glTIEG1MBWfW16r6IVDdztLl6kTBOmdTcnenI_Kpuw

{
    "id": 2
}

###

POST http://localhost:8080/api/orders/sendUpdate/86